###
POST http://localhost:4000/employee-api/employee
Content-Type: application/json

{
    "name":"joyce",
    "mobile":1234567890,
    "designation":"ceo",
    "companyName":"abc",
    "email":"joyce@gmail.com"
}

###
GET http://localhost:4000/employee-api/employees

###
DELETE http://localhost:4000/employee-api/employee/69ca1f5a04152e75fc588901


###
PUT http://localhost:4000/employee-api/employee/
Content-Type:application/json

{
"name":"joyce",
    "mobile":9999999999,
    "designation":"ceo",
    "companyName":"abc",
    "email":"joyce@gmail.com"
}